# Run linters automatically on pull requests.
name: Lint rcpputils
on:
  pull_request:

jobs:
  ament_copyright:
    name: ament_copyright
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: copyright
        package-name: rcpputils

  ament_xmllint:
    name: ament_xmllint
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: xmllint
        package-name: rcpputils

  ament_lint_cpp: # Linters applicable to C++ packages
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-lint@0.0.5
      with:
        linter: ${{ matrix.linter }}
        package-name: rcpputils
