language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="crystal" ROS_REPO=testing
    - ROS_DISTRO="crystal" ROS_REPO=main
    - ROS_DISTRO="dashing" ROS_REPO=testing
    - ROS_DISTRO="dashing" ROS_REPO=main
    - ROS_DISTRO="eloquent" ROS_REPO=testing

install:
  - git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
