# User input (e.g. button presses) related to the factory ADAS functions
std_msgs/Header header

bool btn_cc_on          # Cruise Control on
bool btn_cc_off         # Cruise Control off
bool btn_cc_on_off      # Cruise Control on/off toggle
bool btn_cc_set_inc     # Cruise Control set/speed +
bool btn_cc_set_dec     # Cruise Control set/speed -
bool btn_cc_res         # Cruise Control resume
bool btn_cc_cncl        # Cruise Control cancel
bool btn_cc_res_cncl    # Cruise Control resume/cancle toggle
bool btn_acc_gap_inc    # Adaptive Cruise Control gap -
bool btn_acc_gap_dec    # Adaptive Cruise Control gap +
bool btn_lka_on         # Lane Keep Assist off
bool btn_lka_off        # Lane Keep Assist on
bool btn_lka_on_off     # Lane Keep Assist on/off toggle
