# Inputs (e.g. button presses) for in-vehicle menus
std_msgs/Header header

bool str_whl_left_btn_left
bool str_whl_left_btn_down
bool str_whl_left_btn_right
bool str_whl_left_btn_up
bool str_whl_left_btn_ok

bool str_whl_right_btn_left
bool str_whl_right_btn_down
bool str_whl_right_btn_right
bool str_whl_right_btn_up
bool str_whl_right_btn_ok

bool cntr_cons_btn_left
bool cntr_cons_btn_down
bool cntr_cons_btn_right
bool cntr_cons_btn_up
bool cntr_cons_btn_ok
